---
services:
  telegram-bot-api-server:
    image: vcaldo/telegram-bot-api
    container_name: telegram-bot-api-server
    env_file:
      - secrets.env
    ports:
      - 8081:8081
    volumes:
      - telegram-bot-api-server-storage:/storage      
    entrypoint: [
      "telegram-bot-api",
      "--local",
      "--dir=/storage",
      "--verbosity=1"
      ]
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: unless-stopped  
  bot:
    image: bot:latest
    container_name: bot
    build:
      context: bot/
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      - LOCAL_TELEGRAM_BOT_API_URL=http://telegram-bot-api-server:8081
      - TRANSMISSION_URL=transmission
      - REDIS_ADDR=redis:6379
    env_file:
      - secrets.env
    volumes:
      - transmission-downloads:/downloads
      - telegram-bot-api-server-storage:/storage
    depends_on:
      - telegram-bot-api-server
      - transmission
    restart: unless-stopped
  splitter:
    image: splitter:latest
    container_name: splitter
    build:
      context: splitter/
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      - TRANSMISSION_URL=transmission
      - REDIS_ADDR=redis:6379
    volumes:
      - transmission-downloads:/downloads
    depends_on:
      - redis
    restart: unless-stopped
volumes:
  redis-data:
    driver: 
      - local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/redis_data
  telegram-bot-api-server-storage:
    driver: 
      - local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/telegram_bot_api_server_storage
  transmission-config:
    driver: 
      - local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/transmission_config 
  transmission-downloads:
    driver: 
      - local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/transmission_downloads